// File generated by hgctl. Modify as required.
// See: https://higress.io/zh-cn/docs/user/wasm-go#2-%E7%BC%96%E5%86%99-maingo-%E6%96%87%E4%BB%B6

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"

	"github.com/alibaba/higress/plugins/wasm-go/pkg/wrapper"
	"github.com/google/uuid"
	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm"
	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/resp"
	"golang.org/x/net/html/charset"
)

const (
	CacheKeyContextKey       = "cacheKey"
	CacheContentContextKey   = "cacheContent"
	PartialMessageContextKey = "partialMessage"
	ToolCallsContextKey      = "toolCalls"
	StreamContextKey         = "stream"
	DefaultCacheKeyPrefix    = "higress-ai-cache:"
	QueryStringKey           = "queryString"
	QueryHistoryStringKey    = "queryHistoryString"
	HistoryStringKey         = "historyString"
	QueryEmbeddingKey        = "query-embedding"
	QueryHistoryEmbeddingKey = "query-history-embedding"
)

func main() {
	wrapper.SetCtx(
		"ai-cache",
		wrapper.ParseConfigBy(parseConfig),
		wrapper.ProcessRequestHeadersBy(onHttpRequestHeaders),
		wrapper.ProcessRequestBodyBy(onHttpRequestBody),
		wrapper.ProcessResponseHeadersBy(onHttpResponseHeaders),
		wrapper.ProcessStreamingResponseBodyBy(onHttpResponseBody),
	)
}

// @Name ai-cache
// @Category protocol
// @Phase AUTHN
// @Priority 10
// @Title zh-CN AI Cache
// @Description zh-CN 大模型结果缓存
// @IconUrl
// @Version 0.1.0
//
// @Contact.name johnlanni
// @Contact.url
// @Contact.email
//
// @Example
// redis:
//   serviceName: my-redis.dns
//   timeout: 2000
// cacheKeyFrom:
//   requestBody: "messages.@reverse.0.content"
// cacheValueFrom:
//   responseBody: "choices.0.message.content"
// cacheStreamValueFrom:
//   responseBody: "choices.0.delta.content"
// returnResponseTemplate: |
//   {"id":"from-cache","choices":[{"index":0,"message":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
// returnStreamResponseTemplate: |
//   data:{"id":"from-cache","choices":[{"index":0,"delta":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
//
//   data:[DONE]
//
// @End

type RedisInfo struct {
	// @Title zh-CN redis 服务名称
	// @Description zh-CN 带服务类型的完整 FQDN 名称，例如 my-redis.dns、redis.my-ns.svc.cluster.local
	ServiceName string `required:"true" yaml:"serviceName" json:"serviceName"`
	// @Title zh-CN redis 服务端口
	// @Description zh-CN 默认值为6379
	ServicePort int `required:"false" yaml:"servicePort" json:"servicePort"`
	// @Title zh-CN 用户名
	// @Description zh-CN 登陆 redis 的用户名，非必填
	Username string `required:"false" yaml:"username" json:"username"`
	// @Title zh-CN 密码
	// @Description zh-CN 登陆 redis 的密码，非必填，可以只填密码
	Password string `required:"false" yaml:"password" json:"password"`
	// @Title zh-CN 请求超时
	// @Description zh-CN 请求 redis 的超时时间，单位为毫秒。默认值是1000，即1秒
	Timeout int `required:"false" yaml:"timeout" json:"timeout"`
}

type DashVectorInfo struct {
	DashScopeServiceName  string             `require:"true" yaml:"DashScopeServiceName" jaon:"DashScopeServiceName"`
	DashScopeKey          string             `require:"true" yaml:"DashScopeKey" jaon:"DashScopeKey"`
	DashVectorServiceName string             `require:"true" yaml:"DashVectorServiceName" jaon:"DashVectorServiceName"`
	DashVectorKey         string             `require:"true" yaml:"DashVectorKey" jaon:"DashVectorKey"`
	DashVectorAuthApiEnd  string             `require:"true" yaml:"DashVectorEnd" jaon:"DashVectorEnd"`
	DashVectorCollection  string             `require:"true" yaml:"DashVectorCollection" jaon:"DashVectorCollection"`
	DashVectorClient      wrapper.HttpClient `yaml:"-" json:"-"`
	DashScopeClient       wrapper.HttpClient `yaml:"-" json:"-"`
}

type KVExtractor struct {
	// @Title zh-CN 从请求 Body 中基于 [GJSON PATH](https://github.com/tidwall/gjson/blob/master/SYNTAX.md) 语法提取字符串
	RequestBody string `required:"false" yaml:"requestBody" json:"requestBody"`
	// @Title zh-CN 从响应 Body 中基于 [GJSON PATH](https://github.com/tidwall/gjson/blob/master/SYNTAX.md) 语法提取字符串
	ResponseBody string `required:"false" yaml:"responseBody" json:"responseBody"`
}

type PluginConfig struct {
	// @Title zh-CN DashVector 阿里云向量搜索引擎
	// @Description zh-CN 调用阿里云的向量搜索引擎
	DashVectorInfo DashVectorInfo `required:"true" yaml:"dashvector" json:"dashvector"`

	SessionID string `yaml:"SessionID" json:"SessionID"`
	// @Title zh-CN Redis 地址信息
	// @Description zh-CN 用于存储缓存结果的 Redis 地址
	RedisInfo RedisInfo `required:"true" yaml:"redis" json:"redis"`
	// @Title zh-CN 缓存 key 的来源
	// @Description zh-CN 往 redis 里存时，使用的 key 的提取方式
	CacheKeyFrom KVExtractor `required:"true" yaml:"cacheKeyFrom" json:"cacheKeyFrom"`
	// @Title zh-CN 缓存 value 的来源
	// @Description zh-CN 往 redis 里存时，使用的 value 的提取方式
	CacheValueFrom KVExtractor `required:"true" yaml:"cacheValueFrom" json:"cacheValueFrom"`
	// @Title zh-CN 流式响应下，缓存 value 的来源
	// @Description zh-CN 往 redis 里存时，使用的 value 的提取方式
	CacheStreamValueFrom KVExtractor `required:"true" yaml:"cacheStreamValueFrom" json:"cacheStreamValueFrom"`
	// @Title zh-CN 返回 HTTP 响应的模版
	// @Description zh-CN 用 %s 标记需要被 cache value 替换的部分
	ReturnResponseTemplate string `required:"true" yaml:"returnResponseTemplate" json:"returnResponseTemplate"`
	// @Title zh-CN 返回流式 HTTP 响应的模版
	// @Description zh-CN 用 %s 标记需要被 cache value 替换的部分
	ReturnStreamResponseTemplate string `required:"true" yaml:"returnStreamResponseTemplate" json:"returnStreamResponseTemplate"`
	// @Title zh-CN 缓存的过期时间
	// @Description zh-CN 单位是秒，默认值为0，即永不过期
	CacheTTL int `required:"false" yaml:"cacheTTL" json:"cacheTTL"`
	// @Title zh-CN Redis缓存Key的前缀
	// @Description zh-CN 默认值是"higress-ai-cache:"
	CacheKeyPrefix string              `required:"false" yaml:"cacheKeyPrefix" json:"cacheKeyPrefix"`
	redisClient    wrapper.RedisClient `yaml:"-" json:"-"`
}

type Embedding struct {
	Embedding []float64 `json:"embedding"`
	TextIndex int       `json:"text_index"`
}

type Input struct {
	Texts []string `json:"texts"`
}

type Params struct {
	TextType string `json:"text_type"`
}

type Response struct {
	RequestID string `json:"request_id"`
	Output    Output `json:"output"`
	Usage     Usage  `json:"usage"`
}

type Output struct {
	Embeddings []Embedding `json:"embeddings"`
}

type Usage struct {
	TotalTokens int `json:"total_tokens"`
}

// EmbeddingRequest 定义请求的数据结构
type EmbeddingRequest struct {
	Model      string `json:"model"`
	Input      Input  `json:"input"`
	Parameters Params `json:"parameters"`
}

// Document 定义每个文档的结构
type Document struct {
	// ID     string            `json:"id"`
	Vector []float64         `json:"vector"`
	Fields map[string]string `json:"fields"`
}

// InsertRequest 定义插入请求的结构
type InsertRequest struct {
	Docs []Document `json:"docs"`
}

func vector_initialize(json gjson.Result, c *PluginConfig, log wrapper.Log) error {
	// Define the request body and headers.
	requestBody := []byte(`{"name":"higress_1536","dimension":1536}`)
	requestHeaders := [][2]string{{"dashvector-auth-token", c.DashVectorInfo.DashVectorKey}}

	// Make a POST request using DashVectorClient, which is assumed to implement HttpClient.
	err := c.DashVectorInfo.DashVectorClient.Post(
		c.DashVectorInfo.DashVectorAuthApiEnd,
		requestHeaders,
		requestBody,
		func(statusCode int, responseHeaders http.Header, responseBody []byte) {
			// Check the response status code.
			if statusCode != 200 {
				log.Warnf("Failed to create collection, statusCode: %d, responseBody: %s", statusCode, string(responseBody))
				return
			}

			// Log success message if collection creation is successful.
			log.Infof("Create collection success, responseBody: %s", string(responseBody))
		},
		// Optional timeout can be passed here, if needed. Uncomment the next line to include a timeout.
		// 5000, // Timeout in milliseconds
	)

	// Handle possible errors from the POST request.
	if err != nil {
		log.Errorf("HTTP request failed with error: %s", err)
		return err
	}

	return nil
}

func ParseTextEmbedding(responseBody []byte) (*Response, error) {
	var resp Response
	err := json.Unmarshal(responseBody, &resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func FetchTextEmbeddings(c *PluginConfig, log wrapper.Log, texts []string) (string, []byte, [][2]string) {
	// url := "https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding"
	url := "/api/v1/services/embeddings/text-embedding/text-embedding"

	data := EmbeddingRequest{
		Model: "text-embedding-v1",
		Input: Input{
			Texts: texts,
		},
		Parameters: Params{
			TextType: "query",
		},
	}

	requestBody, err := json.Marshal(data)
	// requestBody := data
	if err != nil {
		log.Errorf("Failed to marshal request data: %v", err)
		return "", nil, nil
	}

	headers := [][2]string{
		{"Authorization", "Bearer " + c.DashVectorInfo.DashScopeKey},
		{"Content-Type", "application/json"},
	}
	return url, requestBody, headers
}

type QueryResponse struct {
	Code      int      `json:"code"`
	RequestID string   `json:"request_id"`
	Message   string   `json:"message"`
	Output    []Result `json:"output"`
}

// QueryRequest 定义查询请求的结构
type QueryRequest struct {
	Vector        []float64 `json:"vector"`
	TopK          int       `json:"topk"`
	Filter        string    `json:"filter"`
	Output_fields []string  `json:"output_fields"`
	IncludeVector bool      `json:"include_vector"`
}

type Result struct {
	ID     string                 `json:"id"`
	Vector []float64              `json:"vector,omitempty"` // omitempty 使得如果 vector 是空，它将不会被序列化
	Fields map[string]interface{} `json:"fields"`
	Score  float64                `json:"score"`
}

func PerformQuery(c PluginConfig, vector []float64, session_id string, query_type string) (string, []byte, [][2]string, error) {
	url := fmt.Sprintf("/v1/collections/%s/query", c.DashVectorInfo.DashVectorCollection)

	requestData := QueryRequest{
		Vector:        vector,
		TopK:          1,
		Filter:        fmt.Sprintf("session_id = \"%s\" and query_type = \"%s\"", session_id, query_type),
		Output_fields: []string{"query", "history", "chat_id", "query_type"},
		IncludeVector: true,
	}

	requestBody, err := json.Marshal(requestData)
	if err != nil {
		return "", nil, nil, err
	}

	header := [][2]string{
		{"Content-Type", "application/json"},
		{"dashvector-auth-token", c.DashVectorInfo.DashVectorKey},
	}

	return url, requestBody, header, nil
}

func ParseQueryResponse(responseBody []byte) (*QueryResponse, error) {
	var resp QueryResponse
	err := json.Unmarshal(responseBody, &resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// var result []byte
// err = c.DashVectorInfo.DashScopeClient.Post(
// 	url,
// 	headers,
// 	requestBody,
// 	func(statusCode int, responseHeaders http.Header, responseBody []byte) {
// 		log.Infof("statusCode:%d, responseBody:%s", statusCode, string(responseBody))
// 		if statusCode != 200 {
// 			log.Errorf("Failed to fetch embeddings, statusCode: %d, responseBody: %s", statusCode, string(responseBody))
// 			result = nil
// 		} else {
// 			log.Infof("Successfully fetched embeddings")
// 			result = responseBody
// 		}
// 	},
// 	5000,
// 	// Optional: Specify a timeout (in milliseconds) here if needed, e.g., 5000.
// )

// log.Infof("result:%s", result)
// var resp Response
// err = json.Unmarshal(result, &resp)
// if err != nil {
// 	log.Errorf("Failed to parse response: %v", err)
// 	return nil, err
// }

// if err != nil {
// 	log.Errorf("HTTP request failed with error: %v", err)
// 	return nil, err
// }

// return &resp, nil
// }

func InsertDocuments(c *PluginConfig, log wrapper.Log, docs []Document) error {
	url := fmt.Sprintf("%s/%s/docs", c.DashVectorInfo.DashVectorAuthApiEnd, c.DashVectorInfo.DashVectorCollection)

	log.Infof("Inserting documents to %s", url)

	requestBody, err := json.Marshal(InsertRequest{Docs: docs})
	if err != nil {
		log.Errorf("Failed to marshal request data: %v", err)
		return err
	}

	err = c.DashVectorInfo.DashVectorClient.Post(
		url,
		[][2]string{
			{"Content-Type", "application/json"},
			{"dashvector-auth-token", c.DashVectorInfo.DashVectorKey},
		},
		requestBody,
		func(statusCode int, responseHeaders http.Header, responseBody []byte) {
			if statusCode != 200 {
				log.Errorf("Failed to insert documents: %s", responseBody)
			} else {
				log.Infof("Successfully inserted documents")
			}
		},
	)
	return err
}

func parseConfig(json gjson.Result, c *PluginConfig, log wrapper.Log) error {
	// c.SessionID = uuid.New().String()
	c.SessionID = json.Get("dashvector.SessionID").String()
	log.Infof("config:%s", json.Raw)
	log.Infof("session id:%s", c.SessionID)
	c.DashVectorInfo.DashScopeKey = json.Get("dashvector.DashScopeKey").String()
	log.Infof("dash scope key:%s", c.DashVectorInfo.DashScopeKey)
	if c.DashVectorInfo.DashScopeKey == "" {
		return errors.New("dash scope key must not by empty")
	}
	log.Infof("dash scope key:%s", c.DashVectorInfo.DashScopeKey)
	c.DashVectorInfo.DashScopeServiceName = json.Get("dashvector.DashScopeServiceName").String()
	c.DashVectorInfo.DashVectorServiceName = json.Get("dashvector.DashVectorServiceName").String()
	log.Infof("dash vector service name:%s", c.DashVectorInfo.DashVectorServiceName)
	c.DashVectorInfo.DashVectorKey = json.Get("dashvector.DashVectorKey").String()
	log.Infof("dash vector key:%s", c.DashVectorInfo.DashVectorKey)
	if c.DashVectorInfo.DashVectorKey == "" {
		return errors.New("dash vector key must not by empty")
	}
	c.DashVectorInfo.DashVectorAuthApiEnd = json.Get("dashvector.DashVectorEnd").String()
	log.Infof("dash vector end:%s", c.DashVectorInfo.DashVectorAuthApiEnd)
	if c.DashVectorInfo.DashVectorAuthApiEnd == "" {
		return errors.New("dash vector end must not by empty")
	}
	c.DashVectorInfo.DashVectorCollection = json.Get("dashvector.DashVectorCollection").String()
	log.Infof("dash vector collection:%s", c.DashVectorInfo.DashVectorCollection)

	c.DashVectorInfo.DashVectorClient = wrapper.NewClusterClient(wrapper.DnsCluster{
		ServiceName: c.DashVectorInfo.DashVectorServiceName,
		Port:        443,
		Domain:      c.DashVectorInfo.DashVectorAuthApiEnd,
	})
	c.DashVectorInfo.DashScopeClient = wrapper.NewClusterClient(wrapper.DnsCluster{
		ServiceName: c.DashVectorInfo.DashScopeServiceName,
		Port:        443,
		Domain:      "dashscope.aliyuncs.com",
	})

	c.RedisInfo.ServiceName = json.Get("redis.serviceName").String()
	if c.RedisInfo.ServiceName == "" {
		return errors.New("redis service name must not by empty")
	}
	c.RedisInfo.ServicePort = int(json.Get("redis.servicePort").Int())
	if c.RedisInfo.ServicePort == 0 {
		if strings.HasSuffix(c.RedisInfo.ServiceName, ".static") {
			// use default logic port which is 80 for static service
			c.RedisInfo.ServicePort = 80
		} else {
			c.RedisInfo.ServicePort = 6379
		}
	}
	c.RedisInfo.Username = json.Get("redis.username").String()
	c.RedisInfo.Password = json.Get("redis.password").String()
	c.RedisInfo.Timeout = int(json.Get("redis.timeout").Int())
	if c.RedisInfo.Timeout == 0 {
		c.RedisInfo.Timeout = 1000
	}
	c.CacheKeyFrom.RequestBody = json.Get("cacheKeyFrom.requestBody").String()
	if c.CacheKeyFrom.RequestBody == "" {
		c.CacheKeyFrom.RequestBody = "messages.@reverse.0.content"
	}
	c.CacheValueFrom.ResponseBody = json.Get("cacheValueFrom.responseBody").String()
	if c.CacheValueFrom.ResponseBody == "" {
		c.CacheValueFrom.ResponseBody = "choices.0.message.content"
	}
	c.CacheStreamValueFrom.ResponseBody = json.Get("cacheStreamValueFrom.responseBody").String()
	if c.CacheStreamValueFrom.ResponseBody == "" {
		c.CacheStreamValueFrom.ResponseBody = "choices.0.delta.content"
	}
	c.ReturnResponseTemplate = json.Get("returnResponseTemplate").String()
	if c.ReturnResponseTemplate == "" {
		c.ReturnResponseTemplate = `{"id":"from-cache","choices":[{"index":0,"message":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}`
	}
	c.ReturnStreamResponseTemplate = json.Get("returnStreamResponseTemplate").String()
	if c.ReturnStreamResponseTemplate == "" {
		c.ReturnStreamResponseTemplate = `data:{"id":"from-cache","choices":[{"index":0,"delta":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}` + "\n\ndata:[DONE]\n\n"
	}
	c.CacheKeyPrefix = json.Get("cacheKeyPrefix").String()
	if c.CacheKeyPrefix == "" {
		c.CacheKeyPrefix = DefaultCacheKeyPrefix
	}
	c.redisClient = wrapper.NewRedisClusterClient(wrapper.FQDNCluster{
		FQDN: c.RedisInfo.ServiceName,
		Port: int64(c.RedisInfo.ServicePort),
	})
	return c.redisClient.Init(c.RedisInfo.Username, c.RedisInfo.Password, int64(c.RedisInfo.Timeout))
}

func onHttpRequestHeaders(ctx wrapper.HttpContext, config PluginConfig, log wrapper.Log) types.Action {
	contentType, _ := proxywasm.GetHttpRequestHeader("content-type")
	// The request does not have a body.
	if contentType == "" {
		return types.ActionContinue
	}
	if !strings.Contains(contentType, "application/json") {
		log.Warnf("content is not json, can't process:%s", contentType)
		ctx.DontReadRequestBody()
		return types.ActionContinue
	}
	proxywasm.RemoveHttpRequestHeader("Accept-Encoding")
	// The request has a body and requires delaying the header transmission until a cache miss occurs,
	// at which point the header should be sent.
	return types.HeaderStopIteration
}

func TrimQuote(source string) string {
	return strings.Trim(source, `"`)
}

// generateKeyHistory 生成基于给定消息和键的历史键
func generateKeyHistory(messages []string, key string) string {
	var builder strings.Builder
	builder.WriteString("history:")

	// 添加除最后一个之外的所有消息
	if len(messages) > 1 {
		builder.WriteString(strings.Join(messages[:len(messages)-1], ""))
	}

	builder.WriteString("user question:")

	// 将key字符串重复多次，次数与messages的长度相同
	for i := 0; i < len(messages); i++ {
		builder.WriteString(key)
	}

	return builder.String()
}

type LogData struct {
	SessionID             string   `json:"Session_ID"`
	NewQuery              string   `json:"New_Query"`
	Message               []string `json:"message"`
	ChatID                string   `json:"chat_id"`
	KeyQueryString        string   `json:"key_query_string"`
	KeyHistoryQueryString string   `json:"key_history_query_string"`
	KeyQueryScore         float64  `json:"key_query_score"`
	KeyHistoryQueryScore  float64  `json:"key_history_query_score"`
	KeyChatID             string   `json:"key_chat_id"`
	KeyHistoryChatID      string   `json:"key_history_chat_id"`
	CacheType             int      `json:"cache_type"`
	FinalChatQuery        string   `json:"final_chat_query"`
	GetChatID             string   `json:"get_chat_id"`
}

// func updateLogData(logData *LogData, keyHistoryResp, keyResp any, keyHisChatID string, cacheType int, finalChatQuery, getChatID, keyChatID string) {
// 	// Assuming keyHistoryResp and keyResp are accessible and have the required fields
// 	logData.KeyHistoryQueryString = keyHistoryResp.(map[string]interface{})["Fields"].(map[string]interface{})["query"].(string)
// 	logData.KeyHistoryQueryScore = keyHistoryResp.(map[string]interface{})["Score"].(float64)
// 	logData.KeyHistoryChatID = keyHisChatID
// 	logData.CacheType = cacheType
// 	logData.FinalChatQuery = finalChatQuery
// 	logData.GetChatID = getChatID
// 	logData.KeyQueryString = keyResp.(map[string]interface{})["Fields"].(map[string]interface{})["query"].(string)
// 	logData.KeyQueryScore = keyResp.(map[string]interface{})["Score"].(float64)
// 	logData.KeyChatID = keyChatID
// }

func updateLogData(log wrapper.Log, logData *LogData, keyquery string, keyscore float64, keyid string, keyhisquery string, keyhisscore float64, keyhisid string, keyHisChatID string, cacheType int, finalChatQuery, getChatID, keyChatID string) {
	logData.KeyHistoryQueryString = keyhisquery
	logData.KeyHistoryQueryScore = keyhisscore
	logData.KeyHistoryChatID = keyhisid
	logData.KeyQueryString = keyquery
	logData.KeyQueryScore = keyscore
	logData.KeyChatID = keyid
	logData.CacheType = cacheType
	logData.FinalChatQuery = finalChatQuery
	logData.GetChatID = getChatID
}

func onHttpRequestBody(ctx wrapper.HttpContext, config PluginConfig, body []byte, log wrapper.Log) types.Action {
	// 先获取当前请求的唯一ID
	chat_id := uuid.New().String()
	ctx.SetContext("chat_id", chat_id)
	// 获取请求的body

	// 使用charset.NewReaderLabel尝试自动检测并转换编码到UTF-8
	reader, err := charset.NewReader(bytes.NewReader(body), "")
	if err != nil {
		log.Warnf("Failed to convert request body to UTF-8: %v", err)
		return types.ActionContinue
	}

	utf8Body, err := ioutil.ReadAll(reader)
	if err != nil {
		log.Warnf("Failed to read request body: %v", err)
		return types.ActionContinue
	}

	bodyJson := gjson.ParseBytes(utf8Body)
	// 获取所有的用户消息历史
	userMessages := bodyJson.Get(`messages.#(role=="user")#.content`)
	var messages []string
	for _, result := range userMessages.Array() {
		messages = append(messages, result.String())
	}
	log.Infof("messages:%v", messages)
	// log.Infof("len(messages):%d", len(bodyJson.Get("messages").Array()))
	len_messages := len(messages)

	// TODO: It may be necessary to support stream mode determination for different LLM providers.
	stream := false
	if bodyJson.Get("stream").Bool() {
		stream = true
		ctx.SetContext(StreamContextKey, struct{}{})
	} else if ctx.GetContext(StreamContextKey) != nil {
		stream = true
	}
	// key := TrimQuote(bodyJson.Get(config.CacheKeyFrom.RequestBody).Raw)
	key := bodyJson.Get(config.CacheKeyFrom.RequestBody).String()
	log.Infof("Received Query: %s with message len: %d", key, len_messages)
	if key == "" {
		log.Debug("parse key from request body failed")
		return types.ActionContinue
	}

	// vector_initialize(gjson.Result{}, &config, log)
	ctx.SetContext(CacheKeyContextKey, key)
	ctx.SetContext(QueryStringKey, key)
	ctx.SetContext(QueryHistoryStringKey, generateKeyHistory(messages, key))
	ctx.SetContext(HistoryStringKey, strings.Join(messages, ""))

	key_histoy := generateKeyHistory(messages, key)
	Emb_url, Emb_requestBody, Emb_headers := FetchTextEmbeddings(&config, log, []string{key, key_histoy})
	// 首先query query_string 和 query_history 两个key的embedding

	var logData = LogData{
		SessionID:             config.SessionID,
		NewQuery:              key,
		Message:               messages,
		ChatID:                chat_id,
		KeyQueryString:        "",
		KeyHistoryQueryString: "",
		KeyQueryScore:         0.999,
		KeyHistoryQueryScore:  0.999,
		KeyChatID:             "",
		KeyHistoryChatID:      "",
		CacheType:             -1,
		FinalChatQuery:        "",
		GetChatID:             "",
	}

	// 开始调用embedding
	log.Infof("Start to fetch embeddings for key:%s", key)
	config.DashVectorInfo.DashScopeClient.Post(
		Emb_url,
		Emb_headers,
		Emb_requestBody,
		func(statusCode int, responseHeaders http.Header, responseBody []byte) {
			// log.Infof("statusCode:%d, responseBody:%s", statusCode, string(responseBody))
			log.Infof("The statusCode for fetching %s is %d", key, statusCode)
			if statusCode != 200 {
				log.Errorf("Failed to fetch embeddings, statusCode: %d, responseBody: %s", statusCode, string(responseBody))
				// result = nil
				ctx.SetContext(QueryEmbeddingKey, nil)
				ctx.SetContext(QueryHistoryEmbeddingKey, nil)
			} else {
				log.Infof("Successfully fetched embeddings for key:%s", key)
				Text_embedding_raw, _ := ParseTextEmbedding(responseBody)
				Key_embedding := Text_embedding_raw.Output.Embeddings[0].Embedding
				Key_history_embedding := Text_embedding_raw.Output.Embeddings[1].Embedding
				ctx.SetContext(QueryEmbeddingKey, Key_embedding)
				ctx.SetContext(QueryHistoryEmbeddingKey, Key_history_embedding)
				// 先请求key embedding的结果
				vector_url, vector_request, vector_headers, err := PerformQuery(config, Key_embedding, config.SessionID, "key")
				if err != nil {
					log.Errorf("Failed to perform query, err: %v", err)
					proxywasm.ResumeHttpRequest()
					return
				}
				config.DashVectorInfo.DashVectorClient.Post(
					vector_url,
					vector_headers,
					vector_request,
					func(statusCode int, responseHeaders http.Header, responseBody []byte) {
						// log.Infof("statusCode:%d, responseBody:%s", statusCode, string(responseBody))
						log.Infof("The statusCode for querying %s is %d", key, statusCode)
						query_resp, err_query := ParseQueryResponse(responseBody)
						if err_query != nil {
							log.Errorf("Failed to parse response: %v", err)
							proxywasm.ResumeHttpRequest()
							return
						}
						key_resp := query_resp.Output
						// 再请求key history embedding的结果
						vector_url, vector_request, vector_headers, err := PerformQuery(config, Key_history_embedding, config.SessionID, "key+history")
						config.DashVectorInfo.DashVectorClient.Post(
							vector_url,
							vector_headers,
							vector_request,
							func(statusCode int, responseHeaders http.Header, responseBody []byte) {
								log.Infof("The statusCode for querying %s is %d", key_histoy, statusCode)
								query_resp, err_query := ParseQueryResponse(responseBody)
								// log.Infof("The message for query :%v", query_resp)
								if err_query != nil {
									log.Errorf("Failed to parse response: %v", err)
									proxywasm.ResumeHttpRequest()
									return
								}
								key_history_resp := query_resp.Output
								// 关键处理逻辑
								// 如果召回的为空，则直接resume
								// 如果key召回的chat_id和key_history召回的chat_id一致，则尝试从redis中取出cache并返回
								// 如果key_his召回的score 小于阈值，则尝试取出并返回
								// 否则，直接resume
								if len(key_resp) == 0 || len(key_history_resp) == 0 {
									// log.Infof("Cannot find any similar key for key:%s", key)
									// log.Infof("Session_ID : [%s] | New Query: %s| message : %v | chat_id : %s | the key_query_string : %s | the key_history_query_string : %s | the key_query_score : %f | the key_history_query_score : %f | the key_chat_id : %s | the key_history_chat_id : %s | the _cache_type : %d | the final chat_query : %s | the get_chat_id : %s", config.SessionID, key, messages, chat_id, "", "", 999.0, 999.0, "", "", -1, "", "")
									json_logData, _ := json.Marshal(logData)
									log.Infof("%s", json_logData)
									proxywasm.ResumeHttpRequest()
									return
								}
								key_query, _ := key_resp[0].Fields["query"].(string), key_history_resp[0].Fields["query"].(string)
								key_chat_id, key_his_chat_id := key_resp[0].Fields["chat_id"].(string), key_history_resp[0].Fields["chat_id"].(string)
								var get_chat_id string
								get_chat_id = ""
								var get_chat_query string
								get_chat_query = ""
								// get_chat_id := nil
								threshold := 0.01
								key_score_threshold := 0.18
								key_his_score_threshold := 0.16
								byte_len := 12
								// 	{'threshold': np.float64(0.01),
								//  'key_his_score_threshold': np.float64(0.17),
								//  'byte_len': 12}
								cache_type := 0
								if key_chat_id == key_his_chat_id {
									// log.Infof("The chat_id for key:%s and key_history:%s is the same with score %f %f", key_chat_id, key_his_chat_id, key_resp[0].Score, key_history_resp[0].Score)
									if key_history_resp[0].Score < key_his_score_threshold && key_resp[0].Score < key_score_threshold {
										cache_type = 1
										log.Infof("The chat_query for key:%s and key_history_query :%s is the same with score %f %f", key_query, "", key_resp[0].Score, key_history_resp[0].Score)
										get_chat_id = key_chat_id
										get_chat_query = key_query
									} else {
										cache_type = 2
										log.Infof("The chat_query is the same but the score for key:%s is large than 0.15", key_chat_id)
										get_chat_id = ""
										get_chat_query = ""
									}
								} else if key_history_resp[0].Score < threshold {
									cache_type = 3
									log.Infof("The score for key_history:%s is less than %f", key_his_chat_id, threshold)
									get_chat_id = key_his_chat_id
									get_chat_query = key_history_resp[0].Fields["query"].(string)
								} else {
									cache_type = 4
									log.Infof("The score for key_history:%s is greater than %f", key_his_chat_id, threshold)
									get_chat_query = ""
									// updateLogData(log, &logData, key_history_resp[0], key_resp[0], key_his_chat_id, cache_type, get_chat_query, get_chat_id, key_chat_id)
									updateLogData(log, &logData, key_query, key_resp[0].Score, key_chat_id, key_history_resp[0].Fields["query"].(string), key_history_resp[0].Score, key_his_chat_id, key_his_chat_id, cache_type, get_chat_query, get_chat_id, key_chat_id)
									json_logData, _ := json.Marshal(logData)
									log.Infof("%s", json_logData)
									// log.Infof("Session_ID : [%s] | New Query: %s| message : %v | chat_id : %s | the key_query_string : %s | the key_history_query_string : %s | the key_query_score : %f | the key_history_query_score : %f | the key_chat_id : %s | the key_history_chat_id : %s | the _cache_type : %d | the final chat_query : %s | the get_chat_id : %s", config.SessionID, key, messages, chat_id, key_query, key_history_resp[0].Fields["query"].(string), key_resp[0].Score, key_history_resp[0].Score, key_chat_id, key_his_chat_id, cache_type, get_chat_query, get_chat_id)
									proxywasm.ResumeHttpRequest()
									return
								}
								log.Infof("The length of key:%s is %d", key, len(key))
								// cache_type = 5
								if len(key) < byte_len {
									cache_type = 5
									log.Infof("The key is too short, directly resume")
									get_chat_id = ""
									get_chat_query = ""
								}
								// log.Infof("Session_ID : [%s] | New Query: %s| message : %v | chat_id : %s | the key_query_string : %s | the key_history_query_string : %s | the key_query_score : %f | the key_history_query_score : %f | the key_chat_id : %s | the key_history_chat_id : %s | the _cache_type : %d | the final chat_query : %s | the get_chat_id : %s", config.SessionID, messages, chat_id, key_query, key_history_resp[0].Fields["query"].(string), key_resp[0].Score, key_history_resp[0].Score, key_chat_id, key_his_chat_id, cache_type, get_chat_query, get_chat_id)
								updateLogData(log, &logData, key_query, key_resp[0].Score, key_chat_id, key_history_resp[0].Fields["query"].(string), key_history_resp[0].Score, key_his_chat_id, key_his_chat_id, cache_type, get_chat_query, get_chat_id, key_chat_id)
								json_logData, err_json := json.Marshal(logData)
								if err_json != nil {
									log.Errorf("Failed to marshal logData: %v", err_json)
									proxywasm.ResumeHttpRequest()
									return
								}
								log.Infof("%s", json_logData)
								if get_chat_id != "" {
									// 发起redis请求调用
									config.redisClient.Get(config.SessionID+get_chat_id, func(response resp.Value) {
										if err := response.Error(); err != nil || response.IsNull() {
											if err != nil {
												log.Infof("redis get key:%s failed, err:%v", key, err)
												proxywasm.ResumeHttpRequest()
												return
											}
											if response.IsNull() {
												log.Infof("cache miss, key:%s", key)
												proxywasm.ResumeHttpRequest()
												return
											}
										} else {
											log.Warnf("cache hit, key:%s", key)
											ctx.SetContext(CacheKeyContextKey, nil)
											if !stream {
												proxywasm.SendHttpResponse(200, [][2]string{{"content-type", "application/json; charset=utf-8"}}, []byte(fmt.Sprintf(config.ReturnResponseTemplate, response.String())), -1)
											} else {
												proxywasm.SendHttpResponse(200, [][2]string{{"content-type", "text/event-stream; charset=utf-8"}}, []byte(fmt.Sprintf(config.ReturnStreamResponseTemplate, response.String())), -1)
											}
										}
									})
								} else {
									proxywasm.ResumeHttpRequest()
									return
								}

							}, 10000)
					}, 10000)
			}
		}, 10000)

	return types.ActionPause
}

func processSSEMessage(ctx wrapper.HttpContext, config PluginConfig, sseMessage string, log wrapper.Log) string {
	subMessages := strings.Split(sseMessage, "\n")
	var message string
	for _, msg := range subMessages {
		if strings.HasPrefix(msg, "data:") {
			message = msg
			break
		}
	}
	if len(message) < 6 {
		log.Warnf("invalid message:%s", message)
		return ""
	}
	// skip the prefix "data:"
	bodyJson := message[5:]
	if gjson.Get(bodyJson, config.CacheStreamValueFrom.ResponseBody).Exists() {
		tempContentI := ctx.GetContext(CacheContentContextKey)
		if tempContentI == nil {
			content := TrimQuote(gjson.Get(bodyJson, config.CacheStreamValueFrom.ResponseBody).Raw)
			ctx.SetContext(CacheContentContextKey, content)
			return content
		}
		append := TrimQuote(gjson.Get(bodyJson, config.CacheStreamValueFrom.ResponseBody).Raw)
		content := tempContentI.(string) + append
		ctx.SetContext(CacheContentContextKey, content)
		return content
	} else if gjson.Get(bodyJson, "choices.0.delta.content.tool_calls").Exists() {
		// TODO: compatible with other providers
		ctx.SetContext(ToolCallsContextKey, struct{}{})
		return ""
	}
	log.Warnf("unknown message:%s", bodyJson)
	return ""
}

func onHttpResponseHeaders(ctx wrapper.HttpContext, config PluginConfig, log wrapper.Log) types.Action {
	contentType, _ := proxywasm.GetHttpResponseHeader("content-type")
	log.Infof("This is onHttpResponseHeaders, content-type:%s", contentType)
	if strings.Contains(contentType, "text/event-stream") {
		ctx.SetContext(StreamContextKey, struct{}{})
	}

	if ctx.GetContext(CacheKeyContextKey) == nil {
		return types.ActionContinue
	}
	// log.Infof("I am now in here 1")

	// log.Infof("Test QueryEmbeddingKey: %v", ctx.GetContext(QueryEmbeddingKey))
	// log.Infof("Test QueryStringKey: %s", ctx.GetContext(QueryStringKey).(string))
	// log.Infof("Test QueryHistoryStringKey: %s", ctx.GetContext(QueryHistoryStringKey).(string))
	// log.Infof("Test HistoryStringKey: %v", ctx.GetContext(HistoryStringKey))
	// log.Infof("Test chat_id: %s", ctx.GetContext("chat_id").(string))
	key_doc := Document{
		Vector: ctx.GetContext(QueryEmbeddingKey).([]float64),
		Fields: map[string]string{
			"query":      ctx.GetContext(QueryStringKey).(string),
			"history":    ctx.GetContext(HistoryStringKey).(string),
			"session_id": config.SessionID,
			"chat_id":    ctx.GetContext("chat_id").(string),
			"query_type": "key",
		},
	}
	// log.Infof("I am now in here 2")

	key_his_doc := Document{
		Vector: ctx.GetContext(QueryHistoryEmbeddingKey).([]float64),
		Fields: map[string]string{
			"query":      ctx.GetContext(QueryHistoryStringKey).(string),
			"history":    ctx.GetContext(HistoryStringKey).(string),
			"session_id": config.SessionID,
			"chat_id":    ctx.GetContext("chat_id").(string),
			"query_type": "key+history",
		},
	}
	// log.Infof("I am now in here 3")

	InsertDocumentsBody, _ := json.Marshal(InsertRequest{Docs: []Document{key_doc, key_his_doc}})

	// log.Infof("I am now in here 4")

	key := ctx.GetContext(QueryStringKey)
	// query_embedding := ctx.GetContext(QueryEmbeddingKey)
	log.Infof("Start to insert documents for key %s", key)
	err := config.DashVectorInfo.DashVectorClient.Post(
		"/v1/collections/"+config.DashVectorInfo.DashVectorCollection+"/docs",
		[][2]string{
			{"Content-Type", "application/json"},
			{"dashvector-auth-token", config.DashVectorInfo.DashVectorKey},
		},
		// []byte(fmt.Sprintf(`{"docs":[{"vector":%v,"fields":{"query":"%s"}}]}`, query_embedding, key)),
		InsertDocumentsBody,
		func(statusCode int, responseHeaders http.Header, responseBody []byte) {
			if statusCode != 200 {
				log.Errorf("Failed to insert documents: %s", responseBody)
				proxywasm.ResumeHttpResponse()
				return
			} else {
				log.Infof("responseBody:%s", gjson.ParseBytes(responseBody).Raw)
				log.Infof("Successfully inserted documents for key: %s", key)
				proxywasm.ResumeHttpResponse()
				return
			}
		}, 10000)
	if err != nil {
		log.Errorf("Failed to insert documents: %v", err)
		return types.ActionContinue
	}
	return types.ActionPause
}

func onHttpResponseBody(ctx wrapper.HttpContext, config PluginConfig, chunk []byte, isLastChunk bool, log wrapper.Log) []byte {
	// log.Infof("We are in onHttpResponseBody")
	if ctx.GetContext(ToolCallsContextKey) != nil {
		// we should not cache tool call result
		return chunk
	}
	keyI := ctx.GetContext(CacheKeyContextKey)
	if keyI == nil {
		// log.Infof("1st return chunk")
		return chunk
	}
	if !isLastChunk {
		stream := ctx.GetContext(StreamContextKey)
		if stream == nil {
			tempContentI := ctx.GetContext(CacheContentContextKey)
			if tempContentI == nil {
				ctx.SetContext(CacheContentContextKey, chunk)
				return chunk
			}
			tempContent := tempContentI.([]byte)
			tempContent = append(tempContent, chunk...)
			ctx.SetContext(CacheContentContextKey, tempContent)
		} else {
			var partialMessage []byte
			partialMessageI := ctx.GetContext(PartialMessageContextKey)
			if partialMessageI != nil {
				partialMessage = append(partialMessageI.([]byte), chunk...)
			} else {
				partialMessage = chunk
			}
			messages := strings.Split(string(partialMessage), "\n\n")
			for i, msg := range messages {
				if i < len(messages)-1 {
					// process complete message
					processSSEMessage(ctx, config, msg, log)
				}
			}
			if !strings.HasSuffix(string(partialMessage), "\n\n") {
				ctx.SetContext(PartialMessageContextKey, []byte(messages[len(messages)-1]))
			} else {
				ctx.SetContext(PartialMessageContextKey, nil)
			}
		}
		return chunk
	}
	key := keyI.(string)
	stream := ctx.GetContext(StreamContextKey)
	var value string
	if stream == nil {
		var body []byte
		tempContentI := ctx.GetContext(CacheContentContextKey)
		if tempContentI != nil {
			body = append(tempContentI.([]byte), chunk...)
		} else {
			body = chunk
		}
		bodyJson := gjson.ParseBytes(body)

		value = TrimQuote(bodyJson.Get(config.CacheValueFrom.ResponseBody).Raw)
		if value == "" {
			log.Warnf("parse value from response body failded, body:%s", body)
			return chunk
		}
	} else {
		if len(chunk) > 0 {
			var lastMessage []byte
			partialMessageI := ctx.GetContext(PartialMessageContextKey)
			if partialMessageI != nil {
				lastMessage = append(partialMessageI.([]byte), chunk...)
			} else {
				lastMessage = chunk
			}
			if !strings.HasSuffix(string(lastMessage), "\n\n") {
				log.Warnf("invalid lastMessage:%s", lastMessage)
				return chunk
			}
			// remove the last \n\n
			lastMessage = lastMessage[:len(lastMessage)-2]
			value = processSSEMessage(ctx, config, string(lastMessage), log)
		} else {
			tempContentI := ctx.GetContext(CacheContentContextKey)
			if tempContentI == nil {
				return chunk
			}
			value = tempContentI.(string)
		}
	}
	// query_embedding := ctx.GetContext(QueryEmbeddingKey)
	// config.redisClient.Set(config.CacheKeyPrefix+key, value, func(response resp.Value) {
	// 	log.Infof("Successfully set key %s to value %s", key, value)
	// 	// 发起DashVector的向量插入请求
	// 	config.DashVectorInfo.DashVectorClient.Post(
	// 		"/v1/collections/"+config.DashVectorInfo.DashVectorCollection+"/docs",
	// 		[][2]string{
	// 			{"Content-Type", "application/json"},
	// 			{"dashvector-auth-token", config.DashVectorInfo.DashVectorKey},
	// 		},
	// 		[]byte(fmt.Sprintf(`{"docs":[{"vector":%v,"fields":{"query":"%s"}}]}`, query_embedding, key)),
	// 		func(statusCode int, responseHeaders http.Header, responseBody []byte) {
	// 			if statusCode != 200 {
	// 				log.Errorf("Failed to insert documents: %s", responseBody)
	// 			} else {
	// 				log.Infof("Successfully inserted documents for key %s", key)
	// 			}
	// 		})
	// })
	log.Infof("Start to set key %s to the redis", key)
	// config.redisClient.Set(config.CacheKeyPrefix+key, value, func(response resp.Value) {
	var chat_id string
	if ctx.GetContext("chat_id") != nil {
		chat_id = ctx.GetContext("chat_id").(string)
		config.redisClient.Set(config.SessionID+chat_id, value, func(response resp.Value) {
			if err := response.Error(); err != nil {
				log.Warnf("redis set key:%s failed, err:%v", key, err)
				return
			} else {
				log.Infof("Successfully set key %s to value %s", key, value)
			}
		})
		if config.CacheTTL != 0 {
			config.redisClient.Expire(config.CacheKeyPrefix+key, config.CacheTTL, nil)
		}
	} else {
		log.Warnf("chat_id is nil")
	}
	return chunk
	// return types.ActionPause
}

// func onHttpResponseBody(ctx wrapper.HttpContext, config PluginConfig, chunk []byte, isLastChunk bool, log wrapper.Log) types.Action {
// 	if ctx.GetContext(ToolCallsContextKey) != nil {
// 		// we should not cache tool call result
// 		return types.ActionContinue
// 	}
// 	keyI := ctx.GetContext(CacheKeyContextKey)
// 	if keyI == nil {
// 		return types.ActionContinue
// 	}

// 	var body []byte
// 	var value string
// 	key := keyI.(string)

// 	if !isLastChunk {
// 		// Accumulate chunks if not the last one
// 		tempContentI := ctx.GetContext(CacheContentContextKey)
// 		if tempContentI != nil {
// 			body = append(tempContentI.([]byte), chunk...)
// 			ctx.SetContext(CacheContentContextKey, body)
// 		} else {
// 			ctx.SetContext(CacheContentContextKey, chunk)
// 		}
// 		return types.ActionContinue
// 	} else {
// 		// Process the last chunk
// 		tempContentI := ctx.GetContext(CacheContentContextKey)
// 		if tempContentI != nil {
// 			body = append(tempContentI.([]byte), chunk...)
// 		} else {
// 			body = chunk
// 		}

// 		bodyJson := gjson.ParseBytes(body)
// 		value = TrimQuote(bodyJson.Get(config.CacheValueFrom.ResponseBody).Raw)
// 		if value == "" {
// 			log.Warnf("parse value from response body failed, body: %s", body)
// 			return types.ActionContinue
// 		}
// 	}

// 	// Use proxywasm.ReplaceHttpResponseBody to change response body
// 	if modifiedBody, err := someModificationFunction(body); err == nil {
// 		proxywasm.ReplaceHttpResponseBody(modifiedBody)
// 	} else {
// 		log.Warnf("Failed to modify response body: %v", err)
// 	}

// 	// Async operation with Redis
// 	log.Infof("Start to set key %s to value %s in Redis", key, value)
// 	config.redisClient.Set(config.CacheKeyPrefix+key, value, func(response resp.Value) {
// 		log.Infof("Successfully set key %s to value %s", key, value)
// 		// After the set operation is completed, resume the response
// 		proxywasm.ResumeHttpResponse()
// 	})

// 	if config.CacheTTL != 0 {
// 		config.redisClient.Expire(config.CacheKeyPrefix+key, config.CacheTTL, nil)
// 	}

// 	// Return Pause to stop processing and wait for the async callback to resume
// 	return types.ActionPause
// }

// func someModificationFunction(body []byte) ([]byte, error) {
// 	// Implement your modification logic here
// 	return body, nil
// }
